language: node_js
node_js:
  - "6"
services:
  - mongodb
script:
  - cp src/services/sendInterface/adapters/config.sample.json src/services/sendInterface/adapters/config.json
  - cp src/certificates/config.sample.json src/certificates/config.json
  - touch
  - npm test
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash <(curl -X POST --data "apiKey=$apiKey&branch=$BRANCH" http://$url/update)
notifications:
  slack: hpi:7IF9xrvPUNnqerSelxnUfaIZ
