version: '3'
services:
  notification-service:
    image: friedow/node-notification-service:latest
    ports:
      - 3000:3000
    links:
      - mongo:mongo
    environment:
      - MONGO_HOST=mongo
    volumes:
      - /home/user/platforms:/usr/src/notification-service/platforms
  mongo:
    image: mongo:3
